# Generated by Django 3.1.6 on 2021-03-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalloan',
            old_name='course',
            new_name='gender',
        ),
    ]
