# Generated by Django 3.1.6 on 2021-04-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_creditcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='message',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='subject',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
