# Generated by Django 3.1.6 on 2021-04-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20210405_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='businessloan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=300)),
                ('mobile', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='carloan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=300)),
                ('mobile', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='educationloan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=300)),
                ('mobile', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='homeloan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=300)),
                ('mobile', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='personalloan',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='personalloan',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='personalloan',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personalloan',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personalloan',
            name='last_name',
        ),
        migrations.AddField(
            model_name='personalloan',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personalloan',
            name='your_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalloan',
            name='email',
            field=models.EmailField(max_length=300),
        ),
    ]
